Charts/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/',include('Outrights.urls'))
]

Outrights/urls.py
from django.urls import path
from . import views

app_name='Outrights'

urlpatterns=[
    # path('',views.IndexView.as_view(),name='index'),
    path('',views.IndexView.as_view(),name='index_page'),
    # path('outrights/',views.get_outrights,name='Outrights_form'),
    path('outrights/',views.OutrightsView.as_view(),name='Outrights_form'),
    path('spreads/',views.SpreadsView.as_view(),name='Spreads_form'),
    path('flys/',views.FlysView.as_view(),name='Flys_form'),
    path('customs/',views.CustomsView.as_view(),name='Customs_form')
]

Outrights/models.py
from django.db import models
from import_export import widgets
from django.utils import timezone

class Data(models.Model):
    date=models.CharField(null=True,max_length=20)
    h10=models.FloatField(null=True)
    m10=models.FloatField(null=True)
    u10=models.FloatField(null=True)
    z10=models.FloatField(null=True)
    h11=models.FloatField(null=True)
    m11=models.FloatField(null=True)
    u11=models.FloatField(null=True)
    z11=models.FloatField(null=True)
    h12=models.FloatField(null=True)
    m12=models.FloatField(null=True)
    u12=models.FloatField(null=True)
    z12=models.FloatField(null=True)
    h13=models.FloatField(null=True)
    m13=models.FloatField(null=True)
    u13=models.FloatField(null=True)
    z13=models.FloatField(null=True)
    h14=models.FloatField(null=True)
    m14=models.FloatField(null=True)
    u14=models.FloatField(null=True)
    z14=models.FloatField(null=True)
    h15=models.FloatField(null=True)
    m15=models.FloatField(null=True)
    u15=models.FloatField(null=True)
    z15=models.FloatField(null=True)
    h16=models.FloatField(null=True)
    m16=models.FloatField(null=True)
    u16=models.FloatField(null=True)
    z16=models.FloatField(null=True)
    h17=models.FloatField(null=True)
    m17=models.FloatField(null=True)
    u17=models.FloatField(null=True)
    z17=models.FloatField(null=True)
    h18=models.FloatField(null=True)
    m18=models.FloatField(null=True)
    u18=models.FloatField(null=True)
    z18=models.FloatField(null=True)
    h19=models.FloatField(null=True)
    m19=models.FloatField(null=True)
    u19=models.FloatField(null=True)
    z19=models.FloatField(null=True)

    def __str__(self):
        return self.date

Outrights/forms.py
from django import forms
import re
from django.core.exceptions import ValidationError

outright_choices=[(' ',''),('h10','H10'),('m10','M10'),('u10','U10'),('z10','Z10'),
                  ('h11','H11'),('m11','M11'),('u11','U11'),('z11','Z11'),
                  ('h12','H12'),('m12','M12'),('u12','U12'),('z12','Z12'),
                  ('h13','H13'),('m13','M13'),('u13','U13'),('z13','Z13'),
                  ('h14','H14'),('m14','M14'),('u14','U14'),('z14','Z14'),
                  ('h15','H15'),('m15','M15'),('u15','U15'),('z15','Z15'),
                  ('h16','H16'),('m16','M16'),('u16','U16'),('z16','Z16'),
                  ('h17','H17'),('m17','M17'),('u17','U17'),('z17','Z17'),
                  ('h18','H18'),('m18','M18'),('u18','U18'),('z18','Z18'),
                  ('h19','H19'),('m19','M19'),('u19','U19'),('z19','Z19'),
                  ]

class OutrightsForm(forms.Form):
    outright1 = forms.CharField(label="Choose Outright1",widget=forms.Select(choices=outright_choices))
    outright2 = forms.CharField(label="Choose Outright2", widget=forms.Select(choices=outright_choices))
    outright3 = forms.CharField(label="Choose Outright3", widget=forms.Select(choices=outright_choices))
    outright4 = forms.CharField(label="Choose Outright4", widget=forms.Select(choices=outright_choices))
    years=forms.IntegerField(max_value=4,min_value=1,required=True)

class SpreadsForm(forms.Form):
    outright1=forms.CharField(label="Choose Spread1",widget=forms.Select(choices=outright_choices))
    outright2=forms.CharField(widget=forms.Select(choices=outright_choices))
    outright3 = forms.CharField(label="Choose Spread2", widget=forms.Select(choices=outright_choices))
    outright4 = forms.CharField(widget=forms.Select(choices=outright_choices))
    outright5 = forms.CharField(label="Choose Spread3", widget=forms.Select(choices=outright_choices))
    outright6 = forms.CharField(widget=forms.Select(choices=outright_choices))
    outright7 = forms.CharField(label="Choose Spread4", widget=forms.Select(choices=outright_choices))
    outright8 = forms.CharField(widget=forms.Select(choices=outright_choices))
    years = forms.IntegerField(max_value=4, min_value=1,required=True)

class FlysForm(forms.Form):
    outright1 = forms.CharField(label="Choose Fly1", widget=forms.Select(choices=outright_choices))
    outright2 = forms.CharField(widget=forms.Select(choices=outright_choices))
    outright3 = forms.CharField(widget=forms.Select(choices=outright_choices))
    outright4 = forms.CharField(label="Choose Fly2", widget=forms.Select(choices=outright_choices))
    outright5 = forms.CharField(widget=forms.Select(choices=outright_choices))
    outright6 = forms.CharField(widget=forms.Select(choices=outright_choices))
    outright7 = forms.CharField(label="Choose Fly3", widget=forms.Select(choices=outright_choices))
    outright8 = forms.CharField(widget=forms.Select(choices=outright_choices))
    outright9 = forms.CharField(widget=forms.Select(choices=outright_choices))
    outright10 = forms.CharField(label="Choose Fly4", widget=forms.Select(choices=outright_choices))
    outright11 = forms.CharField(widget=forms.Select(choices=outright_choices))
    outright12 = forms.CharField(widget=forms.Select(choices=outright_choices))
    years = forms.IntegerField(max_value=4, min_value=1,required=True)

class CustomForm(forms.Form):
    expression=forms.CharField(label="Enter the equation to be evaluated",max_length=50)
    years=forms.IntegerField(max_value=4,min_value=1,required=True)
    print("1")
    def clean_expression(self):
        print("2")
        expr=self.cleaned_data['expression']
        pattern=r"^[+-]{0,1}[\d]*[a-zA-Z][0-9]{2}([+-][\d]*[a-zA-Z][0-9]{2})*$"
        if re.match(pattern,expr):
            print("3")
            return expr
        else:
            print("4")
            raise forms.ValidationError("enter a valid expression")

Outrights/views.py
from django.shortcuts import render
from django.views import generic,View
from .models import Data
from .forms import OutrightsForm,SpreadsForm,FlysForm,CustomForm
from django.http import HttpResponse
from .models import Data
from datetime import datetime, timedelta
import calendar
import re

class Helper():
    def get_day(self,outright):
        month = 0
        year = 0
        month_code = ['h', 'm', 'u', 'z']
        month = 3 * (month_code.index(outright[0]) + 1)
        year = 2000 + int(outright[1:3])
        return datetime(year, month, 1).date()

    def get_expiry(self,curr_date):
        cal = calendar.Calendar(0)
        month = cal.monthdatescalendar(curr_date.year, curr_date.month)
        lastweek = month[-1]
        monday = lastweek[0] - timedelta(days=14)
        return monday

    def get_xaxis(self,length,num_years):
        last_month = num_years * 12
        x_axis = [0] * (length - 1) + [last_month]
        mth = last_month - 1
        ct = 1
        for i in range(length - 2, -1, -1):
            if ct == 21:
                x_axis[i] = mth
                mth -= 1
                ct = 0
            else:
                x_axis[i] = ""
                ct += 1
        return x_axis

    def get_valid_data(self,curr_date,num_years):
        expiry_date = self.get_expiry(curr_date)
        start_date = expiry_date - timedelta(days=365.24 * num_years)
        all_dates = Data.objects.all()
        valid_data = []
        for date_object in all_dates:
            temp_date = datetime.strptime(date_object.date, '%m/%d/%Y').date()
            if temp_date >= start_date and temp_date <= expiry_date:
                valid_data.append(date_object)
        return valid_data

class IndexView(generic.ListView):
    template_name = 'Outrights/index.html'
    context_object_name = 'Options'
    def get_queryset(self):
        return ["Outrights","Spreads","Flys","Customs"]


class OutrightsView(generic.TemplateView):
    helper=Helper()
    def get(self, request):
        form = OutrightsForm()
        return render(request, 'Outrights/ui_outrights.html', {'form': form,'method':'get'})
    def post(self,request):
        form = OutrightsForm(request.POST)
        outrights=[]
        for i in range(4):
            outrights.append(request.POST["outright"+str(i+1)])
        if self.CheckNull(outrights):
            return render(request, 'Outrights/ui_outrights.html',
                          {'form': form,'error':"Enter at least one outright"})
        num_years = float(request.POST['years'])
        legend = []
        y_axis = []
        for o_r in outrights:
            if o_r!=' ':
                y_axis.append(self.get_data_for_outright(num_years,o_r))
                legend.append(o_r.upper())
        x_axis_len=max([len(i) for i in y_axis])
        x_axis = self.helper.get_xaxis(x_axis_len, num_years)
        return render(request, 'Outrights/ui_outrights.html',
                      {'form': form, 'x_axis': x_axis, 'y_axis': y_axis, 'legend': legend,'method':'post'})

    def get_data_for_outright(self,num_years, outright):
        curr_date = self.helper.get_day(outright)
        valid_data = self.helper.get_valid_data(curr_date, num_years)
        y_axis = []
        for object in valid_data:
            if getattr(object, outright):
                y_axis.append(getattr(object, outright))
        return y_axis
    def CheckNull(self,l):
        for i in l:
            if i!=' ':
                return False
        return True

class SpreadsView(generic.TemplateView):
    helper=Helper()
    def get(self, request):
        form = SpreadsForm()
        return render(request, 'Outrights/ui_spreads.html', {'form': form,'method':'get'})
    def post(self,request):
        form = SpreadsForm(request.POST)
        outrights = []
        for i in range(8):
            outrights.append(request.POST["outright" + str(i + 1)])
        if self.CheckNull(outrights):
            return render(request, 'Outrights/ui_spreads.html',
                          {'form': form,'error':"Enter at least one spread"})
        num_years = float(request.POST['years'])
        legend = []
        y_axis = []
        for i in range(0,8,2):
            if outrights[i] != ' ' and outrights[i+1] != ' ':
                y_axis.append(self.get_data_for_spread(num_years, outrights[i], outrights[i+1]))
                legend.append(outrights[i].upper() + "-" + outrights[i+1].upper())
        x_axis_len = max([len(i) for i in y_axis])
        x_axis = self.helper.get_xaxis(x_axis_len, num_years)
        return render(request, 'Outrights/ui_spreads.html',
                      {'form': form, 'x_axis': x_axis, 'y_axis': y_axis, 'legend': legend,'method':'post'})

    def get_data_for_spread(self,num_years,outright1,outright2):
        curr_date=min(self.helper.get_day(outright1),self.helper.get_day(outright2))
        valid_data=self.helper.get_valid_data(curr_date,num_years)
        y_axis=[]
        for object in valid_data:
            if getattr(object, outright1) and getattr(object,outright2):
                y_axis.append(getattr(object, outright1)-getattr(object,outright2))
        return y_axis

    def CheckNull(self,l):
        l=[l[i]+l[i+1] for i in range(0,len(l),2)]
        for i in l:
            if ' ' not in i:
                return False
        return True

class FlysView(generic.TemplateView):
    helper=Helper()
    def get(self,request):
        form = FlysForm()
        return render(request, 'Outrights/ui_flys.html', {'form': form,'method':'get'})
    def post(self,request):
        form = FlysForm(request.POST)
        outrights = []
        for i in range(12):
            outrights.append(request.POST["outright" + str(i + 1)])
        if self.CheckNull(outrights):
            return render(request, 'Outrights/ui_flys.html',
                          {'form': form,'error':"Enter at least one fly"})
        num_years = float(request.POST['years'])
        legend = []
        y_axis = []
        for i in range(0,12,3):
            if outrights[i] != ' ' and outrights[i+1] != ' ' and outrights[i+2] != ' ':
                y_axis.append(self.get_data_for_fly(num_years, outrights[i], outrights[i+1], outrights[i+2]))
                legend.append(outrights[i].upper() + "-" + outrights[i+1].upper() + "-" + outrights[i+2].upper())
        x_axis_len = max([len(i) for i in y_axis])
        x_axis = self.helper.get_xaxis(x_axis_len, num_years)
        return render(request, 'Outrights/ui_flys.html',
                      {'form': form, 'x_axis': x_axis, 'y_axis': y_axis, 'legend': legend,'method':'post'})

    def get_data_for_fly(self,num_years,outright1,outright2,outright3):
        curr_date=min(self.helper.get_day(outright1),self.helper.get_day(outright2),self.helper.get_day(outright3))
        valid_data=self.helper.get_valid_data(curr_date,num_years)
        y_axis=[]
        for object in valid_data:
            if getattr(object, outright1) and getattr(object,outright2) and getattr(object,outright3):
                y_axis.append(getattr(object, outright1)-2*getattr(object,outright2)+getattr(object,outright3))
        return y_axis

    def CheckNull(self,l):
        l=[l[i]+l[i+1]+l[i+2] for i in range(0,len(l),3)]
        for i in l:
            if ' ' not in i:
                return False
        return True

class CustomsView(generic.TemplateView):
    helper=Helper()
    def get(self,request):
        form = CustomForm()
        return render(request, 'Outrights/ui_customs.html', {'form': form,'method':'get'})
    def post(self,request):
        form = CustomForm(request.POST)
        if form.is_valid():
            expr = request.POST['expression'].lower()
            num_years = float(request.POST['years'])
            expr = expr.replace("+", "#+")
            expr = expr.replace("-", "#-")
            if expr[0]!="#":
                expr = "#+" + expr
            print(expr)
            outrights = expr.split("#")
            outrights = [i for i in outrights if i != '']
            print(outrights)
            y_axis = [self.get_data_for_customs(num_years, outrights)]
            x_axis = self.helper.get_xaxis(len(y_axis[0]), num_years)
            legend = [''.join(outrights).upper()]
            return render(request, 'Outrights/ui_customs.html',
                          {'form': form, 'x_axis': x_axis, 'y_axis': y_axis, 'legend': legend,'method':'post'})
        else:
            form=CustomForm()
            return render(request, 'Outrights/ui_customs.html',
                          {'form': form,'error':"Please enter a valid expression"})

    def evaluate(self,expr):
        pattern=r"^([+-])([\d]*)([a-zA-Z])([\d]{2})"
        match=re.match(pattern,expr)
        return [match.group(1),match.group(2),match.group(3)+match.group(4)]

    def get_data_for_customs(self,num_years,outrights):
        outrights_names=[]
        for o_r in outrights:
            index=o_r.find(next(filter(str.isalpha, o_r)))
            outrights_names.append(o_r[index:])
        curr_date=min([self.helper.get_day(i) for i in outrights_names])
        valid_data=self.helper.get_valid_data(curr_date,num_years)
        y_axis=[]
        for object in valid_data:
            check=list(map(lambda x:getattr(object,x),outrights_names))
            y_axis_val=0
            if not (None in check):
                evaluated=list(map(lambda x:self.evaluate(x),outrights))
                for i in evaluated:
                    if i[1]=='':
                        i[1]=1
                    if i[0]=="+":
                        y_axis_val+=getattr(object,i[2])*int(i[1])
                    elif i[0]=="-":
                        y_axis_val -= getattr(object, i[2]) * int(i[1])
                y_axis.append(y_axis_val)
        return y_axis

Outrights/templates/Outrights/fix_dpi.html
<script type="text/javascript">
    let dpi = window.devicePixelRatio;
    let canvas = document.getElementById('chart');
    let ctx = canvas.getContext('2d');
    function fix_dpi() {
        let style_height = +getComputedStyle(canvas).getPropertyValue("height").slice(0, -2);
        let style_width = +getComputedStyle(canvas).getPropertyValue("width").slice(0, -2);
        canvas.setAttribute('height', style_height * dpi);
        canvas.setAttribute('width', style_width * dpi);
    }
    fix_dpi();
    ctx.font = "3vh Arial";
    ctx.textAlign="center";
    ctx.fillText("Chart will be displayed here.",canvas.width/2,canvas.height/2);
</script>

Outrights/templates/Outrights/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>Index</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'Outrights/index.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Barriecito' rel='stylesheet'>
</head>
<body>
    <div class="row">
        <a href="{% url 'Outrights:'|add:Options.0|add:'_form' %}">
            <div class="column" style="background-color:#FFA07A" >{{ Options.0 }}</div>
        </a>
        <a href="{% url 'Outrights:'|add:Options.1|add:'_form' %}">
            <div class="column" style="background-color:#FFD700">{{ Options.1 }}</div>
        </a>
    </div>
    <div class="row">
        <a href="{% url 'Outrights:'|add:Options.2|add:'_form' %}">
            <div class="column" style="background-color:#00FF7F">{{ Options.2 }}</div>
        </a>
        <a href="{% url 'Outrights:'|add:Options.3|add:'_form' %}">
            <div class="column" style="background-color:#40E0D0">{{ Options.3 }}</div>
        </a>
    </div>
</body>
</html>

Outrights/templates/Outrights/reset.html
<script>
    function ClearForm(myform){
        var elements=myform.elements;
        myform.reset();
        for(i=0;i<elements.length;i++){
            var ele=elements[i].type.toLowerCase();
            if (ele=="text" || ele=="number")
                elements[i].value="";
            else if (ele=="select-one")
                elements[i].selectedIndex=0;
        }
    }
    function FixDpi(){
        var element = document.getElementById("chart");
        element.parentNode.removeChild(element);
        var p = document.getElementById("chart-container");
        var newElement = document.createElement("CANVAS");
        newElement.setAttribute('id', "chart");
        p.appendChild(newElement);
        let dpi = window.devicePixelRatio;
        let canvas = document.getElementById('chart');
        let ctx = canvas.getContext('2d');
        function fix_dpi() {
            let style_height = +getComputedStyle(canvas).getPropertyValue("height").slice(0, -2);
            let style_width = +getComputedStyle(canvas).getPropertyValue("width").slice(0, -2);
            canvas.setAttribute('height', style_height * dpi);
            canvas.setAttribute('width', style_width * dpi);
        };
        fix_dpi();
        console.log("h");
        ctx.font = "3vh Arial";
        ctx.textAlign="center";
        ctx.fillText("Chart will be displayed here.",canvas.width/2,canvas.height/2);
    }
</script>

Outrights/templates/Outrights/ui_customs.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Custom</title>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.bundle.min.js">
    </script>
    {% include 'Outrights/reset.html' %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'Outrights/style.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Arbutus Slab' rel='stylesheet'>
</head>
<body>
<div class="navbar">
    <a href="{% url 'Outrights:Outrights_form' %}">Outrights</a>
    <a href="{% url 'Outrights:Spreads_form' %}">Spreads</a>
    <a href="{% url 'Outrights:Flys_form' %}">Flys</a>
    <a class="active"  href="{% url 'Outrights:Customs_form' %}">Customs</a>
    <a href="{% url 'Outrights:index_page' %}">Back to menu</a>
</div>
<form id="f" action="" method="post">
    {% csrf_token %}
    {% for field in form %}
    {{ field.label_tag }}<label>&nbsp;&nbsp;&nbsp;</label>{{ field }}<br><br>
    {% endfor %}
    <input type="submit" value=" View Chart ">
    <input type="button" value=" Reset " name="clear" onclick="ClearForm(this.form);FixDpi();"><br><br>
    {% if error %}
    <script>alert("{{ error }}")</script>
    {% endif %}
    <div id="chart-container">
        <canvas id="chart"></canvas>
        {% ifequal method "get" %}
            {% include 'Outrights/fix_dpi.html' %}
        {% else %}
            {% if error %}
                {% include 'Outrights/fix_dpi.html' %}
            {%  else %}
                {% include 'Outrights/result.html' %}
            {% endif %}
        {% endifequal %}
    </div>
</form>
</body>
</html>

Outrights/templates/Outrights/ui_flys.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Flys</title>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.bundle.min.js">
    </script>
    {% include 'Outrights/reset.html' %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'Outrights/style.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Arbutus Slab' rel='stylesheet'>
</head>
<body>
<div class="navbar">
    <a href="{% url 'Outrights:Outrights_form' %}">Outrights</a>
    <a href="{% url 'Outrights:Spreads_form' %}">Spreads</a>
    <a class="active" href="{% url 'Outrights:Flys_form' %}">Flys</a>
    <a href="{% url 'Outrights:Customs_form' %}">Customs</a>
    <a href="{% url 'Outrights:index_page' %}">Back to menu</a>
</div>
<form action="" method="post">
    {% csrf_token %}
    {{ form.outright1.label_tag }}&nbsp;&nbsp;&nbsp;{{ form.outright1 }}&nbsp;&nbsp;&nbsp;
    {{ form.outright2 }}&nbsp;&nbsp;&nbsp;{{ form.outright3 }}<br><br>
    {{ form.outright4.label_tag }}&nbsp;&nbsp;&nbsp;{{ form.outright4 }}&nbsp;&nbsp;&nbsp;
    {{ form.outright5 }}&nbsp;&nbsp;&nbsp;{{ form.outright6 }}<br><br>
    {{ form.outright7.label_tag }}&nbsp;&nbsp;&nbsp;{{ form.outright7 }}&nbsp;&nbsp;&nbsp;
    {{ form.outright8 }}&nbsp;&nbsp;&nbsp;{{ form.outright9 }}<br><br>
    {{ form.outright10.label_tag }}&nbsp;&nbsp;&nbsp;{{ form.outright10 }}&nbsp;&nbsp;&nbsp;
    {{ form.outright11 }}&nbsp;&nbsp;&nbsp;{{ form.outright12 }}<br><br>
    {{ form.years.label_tag }}&nbsp;&nbsp;&nbsp;{{ form.years }}<br><br>
    <input type="submit" value=" View Chart ">
    <input type="button" value=" Reset " name="clear" onclick="ClearForm(this.form);FixDpi();"><br><br>
    {% if error %}
    <script>alert("{{ error }}")</script>
    {% endif %}
    <div id="chart-container">
        <canvas id="chart"></canvas>
        {% ifequal method "get" %}
            {% include 'Outrights/fix_dpi.html' %}
        {% else %}
            {% if error %}
                {% include 'Outrights/fix_dpi.html' %}
            {%  else %}
                {% include 'Outrights/result.html' %}
            {% endif %}
        {% endifequal %}
    </div>
</form>
</body>
</html>

Outrights/templates/Outrights/ui_outrights.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>Outrights</title>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.bundle.min.js">
    </script>
    {% include 'Outrights/reset.html' %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'Outrights/style.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Arbutus Slab' rel='stylesheet'>
</head>
<body>
<div class="navbar">
    <a class="active" href="{% url 'Outrights:Outrights_form' %}">Outrights</a>
    <a href="{% url 'Outrights:Spreads_form' %}">Spreads</a>
    <a href="{% url 'Outrights:Flys_form' %}">Flys</a>
    <a href="{% url 'Outrights:Customs_form' %}">Customs</a>
    <a href="{% url 'Outrights:index_page' %}">Back to menu</a>
</div>
<form action="" method="post">
    {% csrf_token %}
    {% for field in form %}
    {{ field.label_tag }}<label>&nbsp;&nbsp;&nbsp;</label>{{ field }}<br><br>
    {% endfor %}
    <input type="submit" value=" View Chart ">
    <input type="button" value=" Reset " name="clear" onclick="ClearForm(this.form);FixDpi();"><br><br>
    {% if error %}
    <script>alert("{{ error }}")</script>
    {% endif %}
    <div id="chart-container">
        <canvas id="chart"></canvas>
        {% ifequal method "get" %}
            {% include 'Outrights/fix_dpi.html' %}
        {% else %}
            {% if error %}
                {% include 'Outrights/fix_dpi.html' %}
            {%  else %}
                {% include 'Outrights/result.html' %}
            {% endif %}
        {% endifequal %}
    </div>
</form>
</body>
</html>

Outrights/templates/Outrights/ui_spreads.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Spreads</title>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.bundle.min.js">
    </script>
    {% include 'Outrights/reset.html' %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'Outrights/style.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Arbutus Slab' rel='stylesheet'>
</head>
<body>
<div class="navbar">
    <a href="{% url 'Outrights:Outrights_form' %}">Outrights</a>
    <a class="active" href="{% url 'Outrights:Spreads_form' %}">Spreads</a>
    <a href="{% url 'Outrights:Flys_form' %}">Flys</a>
    <a href="{% url 'Outrights:Customs_form' %}">Customs</a>
    <a href="{% url 'Outrights:index_page' %}">Back to menu</a>
</div>
<form action="" method="post">
    {% csrf_token %}
    {{ form.outright1.label_tag }}&nbsp;&nbsp;&nbsp;{{ form.outright1 }}&nbsp;&nbsp;&nbsp;{{ form.outright2 }}<br><br>
    {{ form.outright3.label_tag }}&nbsp;&nbsp;&nbsp;{{ form.outright3 }}&nbsp;&nbsp;&nbsp;{{ form.outright4 }}<br><br>
    {{ form.outright5.label_tag }}&nbsp;&nbsp;&nbsp;{{ form.outright5 }}&nbsp;&nbsp;&nbsp;{{ form.outright6 }}<br><br>
    {{ form.outright7.label_tag }}&nbsp;&nbsp;&nbsp;{{ form.outright7 }}&nbsp;&nbsp;&nbsp;{{ form.outright8 }}<br><br>
    {{ form.years.label_tag }}&nbsp;&nbsp;&nbsp;{{ form.years }}<br><br>
    <input type="submit" value=" View Chart ">
    <input type="button" value=" Reset " name="clear" onclick="ClearForm(this.form);FixDpi();"><br><br>
    {% if error %}
    <script>alert("{{ error }}")</script>
    {% endif %}
    <div id="chart-container">
        <canvas id="chart"></canvas>
        {% ifequal method "get" %}
            {% include 'Outrights/fix_dpi.html' %}
        {% else %}
            {% if error %}
                {% include 'Outrights/fix_dpi.html' %}
            {%  else %}
                {% include 'Outrights/result.html' %}
            {% endif %}
        {% endifequal %}
    </div>
</form>
</body>
</html>